name: rabiesmol
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pandas=2.2
  - numpy=1.26
  - pyarrow=15.0
  - jinja2=3.1
  - typer=0.9
  - loguru=0.7
  - nbconvert=7.0
  - pyyaml=6.0
  - autodock-vina=1.2.5
  - openbabel=3.1.1
  - pip
  - pip:
    - plotly>=5.0
