name: rabiesmol
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - rdkit=2023.03.3
  - openbabel=3.1.1
  - autodock-vina=1.2.5
  - pandas=2.1.4
  - numpy=1.26.2
  - pyarrow=15.0.2
  - scikit-learn=1.3.2
  - matplotlib=3.8.2
  - seaborn=0.13.1
  - jupyterlab=4.0.10
  - pip
  - pip:
      - deepchem==2.7.1
      - loguru==0.7.2
      - pydantic==2.5.3
