site_name: RabiesMolScreen
repo_url: https://github.com/voroninsergei/RabiesMolScreen
theme:
  name: material
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Workflow: workflow.md
  - CLI: cli.md
  - Development: development.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
  - Changelog: changelog.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.critic
plugins:
  - search
