[tool.poetry]
name = "rabiesmol"
version = "0.1.0"
description = "Pipeline for molecular screening against RABV targets"
authors = ["Your Name <your@email.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
rdkit-pypi = "^2023.3.3"
openbabel-wheel = "^3.1.1.20"
pandas = "^2.1.4"
numpy = "^1.26.2"
scikit-learn = "^1.3.2"
matplotlib = "^3.8.2"
seaborn = "^0.13.1"
deepchem = "^2.7.1"
loguru = "^0.7.2"
pydantic = "^2.5.3"

[tool.poetry.group.dev.dependencies]
black = "^23.12"
ruff = "^0.1.9"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.isort]
profile = "black"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"
isort = "^5.12.0"

[tool.black]
line-length = 100
target-version = ['py310']

[tool.ruff]
line-length = 100
target-version = 'py310'
