# Ruff configuration
line-length = 100
target-version = "py310"

[lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["E203", "W503"]

[lint.isort]
known-third-party = ["rdkit", "pydantic", "loguru", "pandas", "numpy"]
